firstnum = int(input('Input Your First Number: '))
secnum = int(input('Input Your Second Number: '))
thirdnum = int(input('Input Your Third Number: '))
fournum = int(input('Input Your Fourth Number: '))
fifnum = int(input('Input Your Fifth Number: '))
x = float(firstnum)
x2 = complex(firstnum)
print("Float of ",firstnum ,"Equal ",x)
print("Complex of ",firstnum ,"Equal ",x2)
y = float(secnum)
y2 = complex(secnum)
print("Float of ",secnum ,"Equal ",y)
print("Complex of ",secnum ,"Equal ",y2)
z = float(thirdnum)
z2 = complex(thirdnum)
print("Float of ",thirdnum ,"Equal ",z)
print("Complex of ",thirdnum ,"Equal ",z2)
a = float(fournum)
a2 = complex(fournum)
print("Float of ",fournum ,"Equal ",a)
print("Complex of ",fournum ,"Equal ",a2)
b = float(fifnum)
b2 = complex(fifnum)
print("Float of ",fifnum ,"Equal ",b)
print("Complex of ",fifnum ,"Equal ",b2)